[workspace]
resolver = "3"
members = [
    "crates/*/*/*",
]

[workspace.dependencies]
ab-contracts-common = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-common" }
ab-contracts-executor = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-executor" }
ab-contracts-io-type = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-io-type" }
ab-contracts-macros = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-macros" }
ab-contracts-macros-impl = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-macros-impl" }
ab-contracts-slots = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-slots" }
ab-contracts-standards = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-standards" }
ab-contracts-test-utils = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-test-utils" }
ab-contracts-trivial-type-derive = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-trivial-type-derive" }
ab-system-contract-address-allocator = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-address-allocator" }
ab-system-contract-code = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-code" }
ab-system-contract-simple-wallet-base = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-simple-wallet-base" }
ab-system-contract-state = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-state" }
blake3 = { version = "1.6.0", default-features = false }
const-sha1 = "0.3.0"
const_format = "0.2.34"
criterion = { version = "0.5.1", default-features = false }
derive_more = { version = "2.0.1", default-features = false }
halfbrown = "0.3.0"
ident_case = "1.0.1"
no-panic = "0.1.35"
proc-macro2 = "1.0.92"
quote = "1.0.38"
schnorrkel = { version = "0.11.4", default-features = false }
smallvec = "1.14.0"
syn = "2.0.93"
take_mut = "0.2.2"
thiserror = { version = "2.0.11", default-features = false }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[workspace.lints.rust]
rust_2018_idioms = "warn"
missing_debug_implementations = "warn"

[profile.production]
inherits = "release"
lto = "fat"
