[workspace]
resolver = "3"
members = [
    "crates/contracts/*/*",
    "crates/execution/*",
    "crates/shared/*",
]

[workspace.dependencies]
ab-aligned-buffer = { version = "0.0.1", path = "crates/shared/ab-aligned-buffer" }
ab-contracts-common = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-common" }
ab-contracts-io-type = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-io-type" }
ab-contracts-macros = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-macros" }
ab-contracts-macros-impl = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-macros-impl" }
ab-contracts-standards = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-standards" }
ab-contracts-test-utils = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-test-utils" }
ab-contracts-trivial-type-derive = { version = "0.0.1", path = "crates/contracts/core/ab-contracts-trivial-type-derive" }
ab-executor-native = { version = "0.0.1", path = "crates/execution/ab-executor-native" }
ab-executor-slots = { version = "0.0.1", path = "crates/execution/ab-executor-slots" }
ab-system-contract-address-allocator = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-address-allocator" }
ab-system-contract-block = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-block" }
ab-system-contract-code = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-code" }
ab-system-contract-native-token = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-native-token" }
ab-system-contract-simple-wallet-base = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-simple-wallet-base" }
ab-system-contract-state = { version = "0.0.1", path = "crates/contracts/system/ab-system-contract-state" }
ab-transaction = { version = "0.0.1", path = "crates/shared/ab-transaction" }
blake3 = { version = "1.7.0", default-features = false }
const-sha1 = { version = "0.3.0", default-features = false }
const_format = "0.2.34"
criterion = { version = "0.5.1", default-features = false }
derive_more = { version = "2.0.1", default-features = false }
halfbrown = "0.3.0"
ident_case = "1.0.1"
no-panic = "0.1.35"
proc-macro2 = "1.0.94"
quote = "1.0.40"
rand_core = { version = "0.9.3", default-features = false }
rand_chacha = { version = "0.9.0", default-features = false }
schnorrkel = { version = "0.11.4", default-features = false }
smallvec = "1.14.0"
syn = "2.0.100"
take_mut = "0.2.2"
thiserror = { version = "2.0.12", default-features = false }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[workspace.lints.rust]
rust_2018_idioms = "warn"
missing_debug_implementations = "warn"

[profile.production]
inherits = "release"
lto = "fat"

[profile.contract]
inherits = "production"
strip = "symbols"
