[package]
name = "subspace-archiving"
description = "Collection of modules used for dealing with archived state of Subspace Network"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/benches",
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[lib]
# Necessary for CLI options to work on benches
bench = false

[dependencies]
ab-erasure-coding = { workspace = true }
ab-merkle-tree = { workspace = true, features = ["alloc"] }
parity-scale-codec = { workspace = true, features = ["derive"] }
rayon = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
subspace-core-primitives = { workspace = true, features = ["alloc", "scale-codec"] }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rand_core = { workspace = true }
rand_chacha = { workspace = true }

[features]
parallel = [
    "dep:rayon",
    "subspace-core-primitives/parallel",
]
serde = [
    "dep:serde",
    "subspace-core-primitives/serde",
]

[[bench]]
name = "archiving"
harness = false
