[package]
name = "subspace-kzg"
description = "KZG primitives for Subspace Network"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
derive_more = { workspace = true, features = ["full"] }
kzg.workspace = true
rust-kzg-blst.workspace = true
static_assertions.workspace = true
subspace-core-primitives.workspace = true

[dev-dependencies]
rand = { workspace = true, features = ["min_const_gen", "std", "std_rng"] }
rand_core.workspace = true

[features]
default = [
    "std",
]
std = [
    "derive_more/std",
    "kzg/std",
    "rust-kzg-blst/std",
]
