[package]
name = "subspace-erasure-coding"
description = "Polynomial erasure coding implementation used in Subspace Network"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
kzg.workspace = true
# TODO: This is not actually `no_std` compatible yet, see https://github.com/AndersTrier/reed-solomon-simd/pull/63
reed-solomon-simd = { workspace = true }
rust-kzg-blst.workspace = true
subspace-core-primitives = { workspace = true, features = ["alloc"] }
subspace-kzg.workspace = true

[dev-dependencies]
rust-kzg-blst = { workspace = true, features = ["rand"] }
rand.workspace = true

[features]
default = ["std", "parallel"]
std = [
    "kzg/std",
    "rust-kzg-blst/std",
    "subspace-kzg/std",
]
parallel = ["rust-kzg-blst/parallel"]
