[package]
name = "subspace-erasure-coding"
description = "Polynomial erasure coding implementation used in Subspace Network"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
# TODO: This is not actually `no_std` compatible yet, see https://github.com/AndersTrier/reed-solomon-simd/pull/63
reed-solomon-simd = { workspace = true }

[dev-dependencies]
rand.workspace = true
