[package]
name = "ab-merkle-tree"
description = ""
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

# TODO: Benches

[dependencies]
blake3 = { workspace = true }

[dev-dependencies]
rand_core = { workspace = true }
rand_chacha = { workspace = true }

[features]
alloc = []

[lints]
workspace = true
