[book]
title = "Project Abundance"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
language = "en"
multilingual = false

[build]
build-dir = "build"
create-missing = false

[preprocessor.alerts]

[preprocessor.d2]
layout = "elk"

[rust]
# TODO: 2024 doesn't work in CI for reasons that are not very clear right now, consider updating it in the future when
#  2024 is available on stable channel
edition = "2021"

[output.html]
git-repository-url = "https://github.com/nazar-pc/abundance/tree/main/book"
mathjax-support = true
preferred-dark-theme = "ayu"
