[package]
name = "subspace-verification"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Verification primitives for Subspace"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
schnorrkel.workspace = true
subspace-core-primitives.workspace = true
