[package]
name = "subspace-verification"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition = "2021"
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Verification primitives for Subspace"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ab-merkle-tree = { workspace = true }
parity-scale-codec = { workspace = true, optional = true }
schnorrkel.workspace = true
subspace-core-primitives.workspace = true
subspace-erasure-coding = { workspace = true, optional = true }
subspace-kzg = { workspace = true, optional = true }
subspace-proof-of-space.workspace = true
thiserror.workspace = true

[features]
alloc = [
    "ab-merkle-tree/alloc",
    "dep:subspace-erasure-coding",
    "dep:subspace-kzg",
    "subspace-core-primitives/alloc",
]
scale-codec = [
    "alloc",
    "dep:parity-scale-codec",
    "subspace-core-primitives/scale-codec",
]
std = [
    "parity-scale-codec?/std",
    "schnorrkel/std",
    "subspace-erasure-coding?/std",
    "subspace-kzg?/std",
    "thiserror/std",
]
