disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Project Abundance"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Project Abundance main website"
