name: mdbook

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: mdbook-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mdbook:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install mdbook
        uses: taiki-e/install-action@acd25891978b4cdaebd139d3efef606d26513b14 # 2.47.0
        with:
          tool: mdbook@0.4

      - name: Build
        working-directory: book
        run: mdbook build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@15de0f09300eea763baee31dff6c6184995c5f6a # v4.7.2
        with:
          branch: gh-pages
          single-commit: true
          folder: book/build
        if: ${{ github.event_name == 'push' }}
